### ISSUE TITLE
Input Console Size Error

### ISSUE THREAD

**Issue by MarwanG** [fredokun/MrPython#9]
The height of the frame on my PC is practically equal to 0, highly likely due to the fact I use a unique wm. However , I think by fixing the size of the output console to 90% this would fix the problem.

37         self.output_console = Text(self.frame_output, height=parent.winfo_width()*0.9, state='disabled',
38                                    yscrollcommand=self.scrollbar.set)

**Comment by fredokun** [comment]
how about the new layout ?  (cf. pull request #12)

**Comment by MarwanG** [comment]
works nicely
